export const ONE_SECOND_IN_MILLISECOND = 1000;
export const FIVE_MINUTES_IN_MILLISECONDS = 5 * 60 * ONE_SECOND_IN_MILLISECOND;
export const TEN_MINUTES_IN_MILLISECONDS = FIVE_MINUTES_IN_MILLISECONDS * 2;
export const ONE_HOUR_IN_MILLISECONDS = TEN_MINUTES_IN_MILLISECONDS * 6;